using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Morris.Roslynk.Infrastructure.Razor;

/// <summary>
/// Finds and removes unnecessary <c>@using</c> directives in a <c>.razor</c>/<c>.cshtml</c> file. The compiler
/// never reports CS8019 in generated code, so the Razor-generated document is re-parsed as ordinary code
/// (its <c>&lt;auto-generated&gt;</c> marker blanked, offsets unchanged) and compiled in place of the original;
/// each CS8019 using is mapped through its <c>#line</c> directive to the <c>@using</c> line that produced it.
/// Only directives written in the file itself are removed: usings mapped from an imports file such as
/// <c>_Imports.razor</c> or <c>_ViewImports.cshtml</c> are shared by other components and left alone.
/// </summary>
public static partial class RazorUnusedUsings
{
	private const string UnnecessaryUsingId = "CS8019";

	[GeneratedRegex(@"<auto-generated\s*/?>", RegexOptions.IgnoreCase)]
	private static partial Regex AutoGeneratedMarker();

	/// <summary>True for imports files, whose directives apply to every component or view beneath them.</summary>
	public static bool IsImportsFile(string path)
	{
		string name = Path.GetFileName(path);
		return string.Equals(name, "_Imports.razor", StringComparison.OrdinalIgnoreCase)
			|| string.Equals(name, "_ViewImports.cshtml", StringComparison.OrdinalIgnoreCase);
	}

	/// <summary>
	/// Returns <paramref name="updated"/> with the unnecessary <c>@using</c> lines of <paramref name="source"/>
	/// removed (only the first when <paramref name="firstOnly"/>), and how many were removed.
	/// </summary>
	public static async Task<(Solution Updated, int Removed)> RemoveAsync(
		Solution updated,
		RazorSourceDocument source,
		bool firstOnly,
		CancellationToken cancellationToken = default)
	{
		if (source.RazorPath is not string razorPath || source.RazorText is not SourceText razorText || IsImportsFile(razorPath))
			return (updated, 0);

		IReadOnlyList<TextSpan> lines = await FindUnusedLinesAsync(source, razorPath, razorText, cancellationToken);
		if (lines.Count == 0)
			return (updated, 0);
		if (firstOnly)
			lines = [lines[0]];

		SourceText rewritten = razorText.WithChanges(lines.Select(line => new TextChange(line, "")));
		foreach (DocumentId documentId in updated.GetDocumentIdsWithFilePath(razorPath))
		{
			if (updated.GetAdditionalDocument(documentId) is not null)
				updated = updated.WithAdditionalDocumentText(documentId, rewritten);
		}

		return (updated, lines.Count);
	}

	/// <summary>The full lines (including their line break) of the file's unnecessary @using directives, in order.</summary>
	private static async Task<IReadOnlyList<TextSpan>> FindUnusedLinesAsync(RazorSourceDocument source, string razorPath, SourceText razorText, CancellationToken cancellationToken)
	{
		Document generated = source.Document;
		SyntaxTree? tree = await generated.GetSyntaxTreeAsync(cancellationToken);
		Compilation? compilation = await generated.Project.GetCompilationAsync(cancellationToken);
		if (tree is null || compilation is null)
			return [];

		string generatedText = (await tree.GetTextAsync(cancellationToken)).ToString();
		string probeText = AutoGeneratedMarker().Replace(generatedText, match => new string(' ', match.Length));
		SyntaxTree probe = CSharpSyntaxTree.ParseText(
			probeText,
			(CSharpParseOptions)tree.Options,
			path: tree.FilePath + ".probe.cs",
			cancellationToken: cancellationToken);

		Compilation probed = compilation.ReplaceSyntaxTree(tree, probe);
		SyntaxNode probeRoot = await probe.GetRootAsync(cancellationToken);

		var lines = new SortedDictionary<int, TextSpan>();
		foreach (Diagnostic diagnostic in probed.GetSemanticModel(probe).GetDiagnostics(cancellationToken: cancellationToken))
		{
			if (diagnostic.Id != UnnecessaryUsingId)
				continue;

			UsingDirectiveSyntax? directive = probeRoot.FindNode(diagnostic.Location.SourceSpan).FirstAncestorOrSelf<UsingDirectiveSyntax>();
			if (directive?.NamespaceOrType is not NameSyntax name)
				continue;

			FileLinePositionSpan mapped = probe.GetMappedLineSpan(name.Span, cancellationToken);
			if (!mapped.HasMappedPath || !source.MapsToSource(mapped.Path))
				continue;
			if (mapped.StartLinePosition.Line >= razorText.Lines.Count)
				continue;

			TextLine line = razorText.Lines[mapped.StartLinePosition.Line];
			string lineText = line.ToString().Trim();
			if (!lineText.StartsWith("@using", StringComparison.Ordinal) || !lineText.Contains(name.ToString(), StringComparison.Ordinal))
				continue;

			lines[line.Start] = line.SpanIncludingLineBreak;
		}

		return lines.Values.ToArray();
	}
}
