using Microsoft.CodeAnalysis;

namespace GeneratorLib;

/// <summary>
/// Emits declarations no hand-written code mentions by name, so tests can see they resolve anyway: a
/// partial half of a hand-written type, a nested type, a member with a local function, a member only
/// generated code calls, and a type that exists only in generated code.
/// </summary>
[Generator]
public sealed class ShapeGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context) =>
		context.RegisterPostInitializationOutput(static output => output.AddSource("Ctx.g.cs", """
			// <auto-generated/>
			namespace ConsumerLib
			{
				public partial class Ctx
				{
					public int ReadValue2() => 2;

					public int Outer()
					{
						return Inner() + 1;

						static int Inner() => 41;
					}

					public int CallsHelper() => Helper();

					private int Helper() => 3;

					public sealed class Cache
					{
						public bool TryResolve(string key) => key.Length > 0;
					}
				}

				public static class OnlyGenerated
				{
					public const int Answer = 42;
				}
			}
			"""));

	/// <summary>A hand-written declaration sharing a generated member's simple name, in another project.</summary>
	internal static bool TryResolve(string key) => key.Length > 0;
}
